language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE plaette_picker_test;' -U postgres
notifications:
  email: false
deploy:
  api_key:
    secure: HMABwKW5NU+34Mgh6DOhl744Q0nJkH4etgv1oF7yYVUrLNfF3mmvC6mB+WcWwm8g/RgRa5oKGtpEumKRsF3G9DNaI7op3JIC2t8m+kZRCo9D58zmVhLGy9AcFTxFS1l6+HDUoU3MuNPmGvvefyBbaPbEH7KT0oOkWrFpFOWYOIel44GwMhI2Lj9jZJt7Hh4zJG1IcWMXGuAVJpEOBnygSjXB1FnahyuV1kCfq0I0AniJQiy6/TWui8nhAsgJKgh6Kb4Ivf+tQ2RtZI07NoMGOAtFTFER5lQFC0l3JjqsTbiG++sEIQ0PDyE5GW4WMfNy6Ws3gilTM7ZP8h4ocJddLpvm9n08BQKDgdMRxAK+ncX5cgFTow8TeY5Y4ZnZ2i/D9l/L2/tQHyt88njGLm2lzCOyef9WFKCASMYSjAyyam7CoUxrwrq48fLq3KiJ7o+oiqomQwO/PGCqg/c2xfigjVG0qutwnb5ayWsY63gawF/4NTgTLk2iri41UFMC0M+ChMuH/g4xtY8Ao52K7aq4YuqpVNx9PcF5/fE2ih48lnVGUHdv9beUVl2kPwd6IT9joxIz4+sb8Q/dUx5NfeIRCASUyIY69cmkmoY9K7wl+E/feyeK/mWQPCyPLi2W1fdzz6vpDxl6XWv0/IpB7vk1TY46/Xe3EQMrO0WDIiYR+so=
  app: casey-dallavalle-palette
  skip_cleanup: true